# Generated by Django 5.2.17 on 2026-09-18 08:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=2)),
                ('category_name', models.CharField(max_length=120)),
                ('category_max', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('max_points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('IQAC', 'IQAC Coordinator'), ('HOD', 'Head of Department'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='FACULTY', max_length=10)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('batch', models.CharField(help_text='Example: 2025-2029', max_length=20)),
                ('current_semester', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('class12_board', models.CharField(blank=True, max_length=50)),
                ('class12_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('class12_max', models.DecimalField(decimal_places=2, default=600, max_digits=6)),
                ('class12_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('activity_date', models.DateField()),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOD_APPROVED', 'HOD Approved'), ('IQAC_APPROVED', 'IQAC Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.frameworkparameter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('credits', models.DecimalField(decimal_places=1, default=3, max_digits=3)),
                ('max_internal', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('max_external', models.DecimalField(decimal_places=2, default=60, max_digits=6)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'unique_together': {('department', 'semester', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credits_registered', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('credits_earned', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('arrears', models.PositiveSmallIntegerField(default=0)),
                ('result', models.CharField(default='PASS', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOD_APPROVED', 'HOD Approved'), ('IQAC_APPROVED', 'IQAC Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('external', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOD_APPROVED', 'HOD Approved'), ('IQAC_APPROVED', 'IQAC Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
