# Generated by Django 5.2.17 on 2026-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevidence',
            name='academic_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activityevidence',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='activityevidence',
            name='board',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='activityevidence',
            name='marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='activityevidence',
            name='maximum_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='activityevidence',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='activityevidence',
            name='school',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
