# Generated by Django 5.2.17 on 2026-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scoreparameter_alter_profile_role_progresssubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresssubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('HOD_APPROVED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
