# Generated by Django 5.2.17 on 2026-10-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_progresssubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresssubmission',
            name='subtopic',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
